#OSS
oss:
  file:
    #不同的服务器，地址不同
    endpoint: oss-cn-shanghai.aliyuncs.com
    #自己的密钥
    accesskeyid: LTAIUdbUdK01zGD3
    accesskeysecret: G3FhDXtPhKUpgRff0YP3QIz8keq6Pi
    #这个自己创建bucket时的命名，控制台创建也行
    bucketname: photoclub
    #文件路径
    filehost: images
